In [2]:
import h5py
import numpy as np
# filename = 'file.hdf5'
# f = h5py.File(filename, 'r')

In [3]:
path = 'F:/Master Project/Dataset/NTU RGB D/2 Stream/cross_subject/'
filename_train = path+'cs_trn.hdf5'
filename_test = path+'cs_tst.hdf5'
f_train = h5py.File(filename_train, 'r')
f_test = h5py.File(filename_test, 'r')

In [4]:
key_train = list(f_train.keys())
key_test = list(f_test.keys())
print(len(key_train))
print(len(key_test))

39780
16324


### Key

In [5]:
print(key_train[0:5])
print(key_test[0:5])

['S001C001P001R001A001', 'S001C001P001R001A002', 'S001C001P001R001A003', 'S001C001P001R001A004', 'S001C001P001R001A005']
['S001C001P003R001A001', 'S001C001P003R001A002', 'S001C001P003R001A003', 'S001C001P003R001A004', 'S001C001P003R001A005']


### Data X

In [6]:
temp = f_train[key_train[0]] # 1 files
print(temp)
print(temp.shape)
print(temp[0].shape)

<HDF5 dataset "S001C001P001R001A001": shape (2, 103, 25, 3), type "<f4">
(2, 103, 25, 3)
(103, 25, 3)


In [7]:
print(f_test[key_test[0]])

<HDF5 dataset "S001C001P003R001A001": shape (2, 118, 25, 3), type "<f4">


In [8]:
test_num = np.array([[  
                        [0,1,2],
                        [3,4,5]
                     ],
                     [
                         [6,7,8],
                         [9,10,11]
                     ]
                    ])
print(test_num.shape)
print(test_num.reshape((2, 3*2)))

(2, 2, 3)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
temp[0,0] # first person, first frame --> 25 joints 

array([[ 0.2181153 ,  0.1725972 ,  3.785547  ],
       [ 0.2323292 ,  0.4326636 ,  3.714767  ],
       [ 0.2457799 ,  0.6877249 ,  3.633897  ],
       [ 0.2128507 ,  0.8079225 ,  3.581995  ],
       [ 0.1109304 ,  0.6111551 ,  3.716962  ],
       [ 0.100875  ,  0.4286715 ,  3.742593  ],
       [ 0.1186992 ,  0.3428923 ,  3.556542  ],
       [ 0.1165352 ,  0.3173672 ,  3.550741  ],
       [ 0.3449145 ,  0.5740387 ,  3.588655  ],
       [ 0.4211396 ,  0.3847547 ,  3.627778  ],
       [ 0.1918999 ,  0.3189077 ,  3.540756  ],
       [ 0.1298675 ,  0.317039  ,  3.542577  ],
       [ 0.162766  ,  0.1745395 ,  3.778471  ],
       [ 0.1975115 , -0.1360554 ,  3.904381  ],
       [ 0.2442706 , -0.4201995 ,  4.054147  ],
       [ 0.2040377 , -0.476396  ,  4.094294  ],
       [ 0.2699234 ,  0.1678491 ,  3.730005  ],
       [ 0.3105748 , -0.1462299 ,  3.818383  ],
       [ 0.3428889 , -0.433214  ,  3.943258  ],
       [ 0.2951482 , -0.5017325 ,  3.968896  ],
       [ 0.2425592 ,  0.6247278 ,  3.656

In [10]:
shape_d = temp[0].shape
new_sequence = temp[0].reshape((shape_d[0], shape_d[1]*shape_d[2]))
print(new_sequence.shape)
print(new_sequence[0])

(103, 75)
[ 0.2181153   0.1725972   3.785547    0.2323292   0.4326636   3.714767
  0.2457799   0.6877249   3.633897    0.2128507   0.8079225   3.581995
  0.1109304   0.6111551   3.716962    0.100875    0.4286715   3.742593
  0.1186992   0.3428923   3.556542    0.1165352   0.3173672   3.550741
  0.3449145   0.5740387   3.588655    0.4211396   0.3847547   3.627778
  0.1918999   0.3189077   3.540756    0.1298675   0.317039    3.542577
  0.162766    0.1745395   3.778471    0.1975115  -0.1360554   3.904381
  0.2442706  -0.4201995   4.054147    0.2040377  -0.476396    4.094294
  0.2699234   0.1678491   3.730005    0.3105748  -0.1462299   3.818383
  0.3428889  -0.433214    3.943258    0.2951482  -0.5017325   3.968896
  0.2425592   0.6247278   3.656055    0.1200176   0.2955468   3.532409
  0.0989792   0.3459614   3.527539    0.08710064  0.2988889   3.54619
  0.1268453   0.2813963   3.549525  ]


### Data Y

#### see list of attribute key ( for getting key for Y )

In [11]:
temp2 = f_train[key_train[0]]
list( temp2.attrs.keys() )

['label']

In [12]:
temp2.attrs['label'][0:5]  # same way with f_test

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)